FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY packages/shared/package.json ./packages/shared/
COPY server/package.json ./server/
COPY prisma ./prisma/

RUN npm install

COPY packages/shared ./packages/shared
COPY server ./server

RUN npm run build --workspace=@floodroute/shared
RUN npm run build --workspace=@floodroute/server
RUN npx prisma generate --schema=./prisma/schema.postgresql.prisma

EXPOSE 5000

CMD ["node", "server/dist/index.js"]
