import { RiverStation } from '@floodroute/shared';

export class RiversService {
  async getStations(): Promise<RiverStation[]> {
    return [
      {
        id: 'cwc-adyar-01',
        riverName: 'Adyar River',
        station: 'Jafferkhanpet Bridge, Chennai',
        state: 'Tamil Nadu',
        district: 'Chennai',
        currentLevelM: 5.92,
        warningLevelM: 5.5,
        dangerLevelM: 6.8,
        hflLevelM: 7.4,
        trend: 'RISING',
        status: 'WARNING',
        dischargeCusecs: 4500,
        latitude: 13.0234,
        longitude: 80.2056,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-cooum-01',
        riverName: 'Cooum River',
        station: 'Koyambedu Regulator, Chennai',
        state: 'Tamil Nadu',
        district: 'Chennai',
        currentLevelM: 4.15,
        warningLevelM: 4.8,
        dangerLevelM: 5.5,
        hflLevelM: 6.2,
        trend: 'STEADY',
        status: 'NORMAL',
        dischargeCusecs: 2100,
        latitude: 13.0694,
        longitude: 80.1948,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-mithi-01',
        riverName: 'Mithi River',
        station: 'Bandra-Kurla Complex Culvert, Mumbai',
        state: 'Maharashtra',
        district: 'Mumbai Suburban',
        currentLevelM: 3.25,
        warningLevelM: 2.8,
        dangerLevelM: 3.5,
        hflLevelM: 4.1,
        trend: 'RISING',
        status: 'WARNING',
        dischargeCusecs: 3400,
        latitude: 19.0645,
        longitude: 72.868,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-brahma-01',
        riverName: 'Brahmaputra River',
        station: 'D.C. Court Gauge, Guwahati',
        state: 'Assam',
        district: 'Kamrup Metropolitan',
        currentLevelM: 50.18,
        warningLevelM: 48.68,
        dangerLevelM: 49.68,
        hflLevelM: 51.46,
        trend: 'RISING',
        status: 'DANGER',
        dischargeCusecs: 49500,
        latitude: 26.185,
        longitude: 91.745,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-ganga-01',
        riverName: 'Ganga River',
        station: 'Digha Ghat, Patna',
        state: 'Bihar',
        district: 'Patna',
        currentLevelM: 49.25,
        warningLevelM: 49.45,
        dangerLevelM: 50.45,
        hflLevelM: 52.52,
        trend: 'FALLING',
        status: 'NORMAL',
        dischargeCusecs: 32000,
        latitude: 25.642,
        longitude: 85.105,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-yamuna-01',
        riverName: 'Yamuna River',
        station: 'Old Railway Bridge, Delhi',
        state: 'Delhi',
        district: 'Central Delhi',
        currentLevelM: 204.85,
        warningLevelM: 204.5,
        dangerLevelM: 205.33,
        hflLevelM: 208.66,
        trend: 'STEADY',
        status: 'WARNING',
        dischargeCusecs: 18500,
        latitude: 28.662,
        longitude: 77.245,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'cwc-periyar-01',
        riverName: 'Periyar River',
        station: 'Aluva Sivarathri Manappuram, Kochi',
        state: 'Kerala',
        district: 'Ernakulam',
        currentLevelM: 2.8,
        warningLevelM: 3.5,
        dangerLevelM: 4.2,
        hflLevelM: 5.8,
        trend: 'STEADY',
        status: 'NORMAL',
        dischargeCusecs: 6200,
        latitude: 10.108,
        longitude: 76.352,
        lastUpdated: new Date().toISOString(),
      },
    ];
  }
}

export const riversService = new RiversService();
